### ISSUE TITLE
Only the last query on buffer works

### ISSUE THREAD

**Issue by mtellezj** [ahmadnazir/exsqlaim#4]
Hi, I'm getting a very odd behaivor. I have a buffer with two queries (query A at top and query B at bottom):

```mysql
select * from tmp_coberturasGeneradasTiempos
where sucursal_id=110 and fecha='2018-01-07' and hora in (21);

select * from tmp_gen_conexiones where sucursal_id=110
and fecha='2018-01-07' and hora in (21);
```
If I run the first query with `C-c C-c` I get this backtrace:

```
Debugger entered--Lisp error: (error "Invalid use of ‘\\’ in replacement text")
  replace-match("\\p;" nil nil ";\n" nil)
  replace-regexp-in-string("\\(?:;\n\\)" #f(compiled-function (it) #<bytecode 0x17e84e5>) "\nselect * from tmp_gen_conexiones where sucursal_id=110 and fecha='2018-01-07'\nAND hora IN (21) AND fecha='2018-01-07';\n")
  s-replace-all(((";\n" . "\\p;")) "\nselect * from tmp_gen_conexiones where sucursal_id=110 and fecha='2018-01-07'\nAND hora IN (21) AND fecha='2018-01-07';\n")
  exsqlaim-mode--build-query("\nselect * from tmp_gen_conexiones where sucursal_id=110 and fecha='2018-01-07'\nAND hora IN (21) AND fecha='2018-01-07';\n" ((";\n" . "\\p;")))
  exsqlaim-mode--build-query-at-point()
  exsqlaim-mode--send()
  funcall-interactively(exsqlaim-mode--send)
  call-interactively(exsqlaim-mode--send nil nil)
  command-execute(exsqlaim-mode--send)
```

And if I run the second query I get the query's rows. If I move the first query (A) below the second query (B), and now run the query at top (B) then I get the a similar backtrace, but if I run the query A (now at the bottom) this run fine. Any clue why this is happening?

**Comment by ahmadnazir** [comment]
Thanks for reporting this. I realized that I didn't tag release `0.0.2` and you are probably still on `0.0.1`. Can you confirm that and try this on the latest release?

**Comment by mtellezj** [comment]
Hi, thanks for the reply. I'm using release `0.0.2` and get I the same error.  Cheers!

**Comment by ahmadnazir** [comment]
Thanks for confirming that. I have tried this on my end and I am unable to reproduce the problem so let's take it step by step:

- It seems that any query that is on the top throws the exception (provided there is more than 1 query in the buffer). 
- However, in the backtrace I can see query B being processed (the one with table: tmp_gen_conexiones which is the second one). So, It seems that when you are trying to execute the query, for some reason the correct query isn't being picked up.

So, here are a few questions:

- What version of emacs are you using. I am on `GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9) of 2018-08-23`
- Can you confirm that the function bound to `C-c C-c` is `(exsqlaim-mode--send)`?
- If it is, what do you get when you call `(exsqlaim-mode--build-query-at-point)` ( You can do this as: `M-: (exsqlaim-mode--build-query-at-point)`)
- What happens when you call: `(s-replace-all '((";\n" . "\\p;")) "\n test;")`.

If we can't work this out, I'll just create a new release where the print command `\p` is disabled by default (which is causing this issue for you).

Thanks for your time.

**Comment by mtellezj** [comment]
Hi, sorry for the delay. Before follow your steps I reinstall the `s` package and that did the trick. Thanks for you help.
